### ISSUE TITLE
Compute CSA on GT and output prediction mask

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/contrast-agnostic-softseg-spinalcord#23]
# Context

We want to compute CSA on the GT (hard and soft labels) in order to get the initial variability and also on the output prediction mask.
In order to do so, we need also need the discs labels to compute CSA at the same levels on all contrast. Therefore, vertebral levels need to be identified on an anatomical image (T1w or T2w) and propagated on the other contrasts. Since we have the warping fields of all contrast to T2w, it is possible.

# Proposed method:

**For CSA on GT, in `process_data.sh`**
- Add vertebral labeling on T2w if label doesn't exsits
- For all contrast perform resgistration (remove current even if softseg exists)
- Bring disc labels to each contrast space
- Crop the disc label
- Copy cropped label into derivatives of cleaned dataset

**For CSA on prediction mask (create a new processing script to compute CSA):**
- Use disc labels available in the derivatives to compute CSA on the output prediction mask.

**Comment by naga-karthik** [comment]
@sandrinebedard any updates on this? 

Currently, in the plots I am generating, I am using the `.csv` files found in the `results` folder of the `data_processed_clean` folder. BUT, the issue is that these csv files contain the CSAs for _all_ the subjects and we're plotting it along with the model prediction CSAs which only contain subjects from the test set. Basically, it is not an apples-to-apples comparison. 

Do you have any suggestion on how we can generate the GT csv data only for the subjects in the test set?

**Comment by valosekj** [comment]
Maybe we could load all CSV files (the ones with _all_ the subjects and the ones containing _only_ subjects from the test set) as Pandas DataFrames, and we could use test subjects to filter out subjects from _all_ the subjects.

**Comment by sandrinebedard** [comment]
I would go with @valosekj's suggestion, to do the filetring inside the script

**Comment by naga-karthik** [comment]
Seems like this has also been completed since we now have plots with CSA on the GT segmentations. @sandrinebedard could you please link to script or part of the code where this is computed now? Thanks!

**Comment by sandrinebedard** [comment]
Is done in https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/e4171e8ce39bafbb592f1263481107071f8bf3e8/csa_generate_figures/analyse_csa_all_models.py#L295-L297
